//https://de.wikipedia.org/wiki/Liste_der_Bundesstaaten_der_Vereinigten_Staaten
export default [
  {
    name: "Alabama",
    abr: "AL",
    nickname: "Heart of Dixie",
    capitol: "Montgomery",
    area_sqkm: "135.767",
    rank_area: "30",
    population: "5.024.279",
    rank_population: "23",
    density_pop_per_sqkm: "35",
    join_date: "14. Dez. 1819",
    gouveneur: "Kay Ivey (R)"
  },
  {
    name: "Alaska",
    abr: "AK",
    nickname: "Last Frontier",
    capitol: "Juneau",
    area_sqkm: "1.723.337",
    rank_area: "1",
    population: "733.391",
    rank_population: "47",
    density_pop_per_sqkm: "0,41",
    join_date: "3. Jan. 1959",
    gouveneur: "Mike J. Dunleavy (R)"
  },
  {
    name: "Arizona",
    abr: "AZ",
    nickname: "Grand Canyon State",
    capitol: "Phoenix",
    area_sqkm: "295.234",
    rank_area: "6",
    population: "7.151.502",
    rank_population: "16",
    density_pop_per_sqkm: "22",
    join_date: "14. Feb. 1912",
    gouveneur: "Doug Ducey (R)"
  },
  {
    name: "Arkansas",
    abr: "AR",
    nickname: "Natural State",
    capitol: "Little Rock",
    area_sqkm: "137.732",
    rank_area: "29",
    population: "3.011.524",
    rank_population: "32",
    density_pop_per_sqkm: "21",
    join_date: "15. Juni 1836",
    gouveneur: "Asa Hutchinson (R)"
  },
  {
    name: "Colorado",
    abr: "CO",
    nickname: "Centennial State",
    capitol: "Denver",
    area_sqkm: "269.601",
    rank_area: "8",
    population: "5.773.714",
    rank_population: "22",
    density_pop_per_sqkm: "19",
    join_date: "1. Aug. 1876",
    gouveneur: "Jared Polis (D)"
  },
  {
    name: "Connecticut",
    abr: "CT",
    nickname: "Constitution State",
    capitol: "Hartford",
    area_sqkm: "14.357",
    rank_area: "48",
    population: "3.605.944",
    rank_population: "29",
    density_pop_per_sqkm: "249",
    join_date: "9. Jan. 1788",
    gouveneur: "Ned Lamont (D)"
  },
  {
    name: "Delaware",
    abr: "DE",
    nickname: "First State",
    capitol: "Dover",
    area_sqkm: "6.446",
    rank_area: "49",
    population: "989.948",
    rank_population: "45",
    density_pop_per_sqkm: "139",
    join_date: "7. Dez. 1787",
    gouveneur: "John C. Carney (D)"
  },
  {
    name: "Florida",
    abr: "FL",
    nickname: "Sunshine State",
    capitol: "Tallahassee",
    area_sqkm: "170.312",
    rank_area: "22",
    population: "21.538.187",
    rank_population: "3",
    density_pop_per_sqkm: "110",
    join_date: "3. März 1845",
    gouveneur: "Ron DeSantis (R)"
  },
  {
    name: "Georgia",
    abr: "GA",
    nickname: "Peach State",
    capitol: "Atlanta",
    area_sqkm: "153.910",
    rank_area: "24",
    population: "10.711.908",
    rank_population: "9",
    density_pop_per_sqkm: "63",
    join_date: "2. Jan. 1788",
    gouveneur: "Brian Kemp (R)"
  },
  {
    name: "Hawaii",
    abr: "HI",
    nickname: "Aloha State",
    capitol: "Honolulu",
    area_sqkm: "28.313",
    rank_area: "43",
    population: "1.455.271",
    rank_population: "40",
    density_pop_per_sqkm: "48",
    join_date: "21. Aug. 1959",
    gouveneur: "David Ige (D)"
  },
  {
    name: "Idaho",
    abr: "ID",
    nickname: "Gem State",
    capitol: "Boise",
    area_sqkm: "216.643",
    rank_area: "14",
    population: "1.839.106",
    rank_population: "39",
    density_pop_per_sqkm: "7",
    join_date: "3. Juli 1890",
    gouveneur: "Brad Little (R)"
  },
  {
    name: "Illinois",
    abr: "IL",
    nickname: "Land of Lincoln",
    capitol: "Springfield",
    area_sqkm: "149.995",
    rank_area: "25",
    population: "12.812.508",
    rank_population: "5",
    density_pop_per_sqkm: "86",
    join_date: "3. Dez. 1818",
    gouveneur: "J. B. Pritzker (D)"
  },
  {
    name: "Indiana",
    abr: "IN",
    nickname: "Hoosier State",
    capitol: "Indianapolis",
    area_sqkm: "94.326",
    rank_area: "38",
    population: "6.785.528",
    rank_population: "15",
    density_pop_per_sqkm: "69",
    join_date: "11. Dez. 1816",
    gouveneur: "Eric Holcomb (R)"
  },
  {
    name: "Iowa",
    abr: "IA",
    nickname: "Hawkeye State",
    capitol: "Des Moines",
    area_sqkm: "145.746",
    rank_area: "26",
    population: "3.190.369",
    rank_population: "30",
    density_pop_per_sqkm: "21",
    join_date: "28. Dez. 1846",
    gouveneur: "Kim Reynolds (R)"
  },
  {
    name: "Kalifornien",
    abr: "CA",
    nickname: "Golden State",
    capitol: "Sacramento",
    area_sqkm: "423.967",
    rank_area: "3",
    population: "39.538.223",
    rank_population: "1",
    density_pop_per_sqkm: "88",
    join_date: "9. Sep. 1850",
    gouveneur: "Gavin Newsom (D)"
  },
  {
    name: "Kansas",
    abr: "KS",
    nickname: "Sunflower State",
    capitol: "Topeka",
    area_sqkm: "213.100",
    rank_area: "15",
    population: "2.937.880",
    rank_population: "33",
    density_pop_per_sqkm: "13",
    join_date: "29. Jan. 1861",
    gouveneur: "Laura Kelly (D)"
  },
  {
    name: "Kentucky",
    abr: "KY",
    nickname: "Bluegrass State",
    capitol: "Frankfort",
    area_sqkm: "104.656",
    rank_area: "37",
    population: "4.505.836",
    rank_population: "26",
    density_pop_per_sqkm: "41",
    join_date: "1. Juni 1792",
    gouveneur: "Andy Beshear (D)"
  },
  {
    name: "Louisiana",
    abr: "LA",
    nickname: "Pelican State",
    capitol: "Baton Rouge",
    area_sqkm: "135.659",
    rank_area: "31",
    population: "4.657.757",
    rank_population: "25",
    density_pop_per_sqkm: "33",
    join_date: "30. Apr. 1812",
    gouveneur: "John Bel Edwards (D)"
  },
  {
    name: "Maine",
    abr: "ME",
    nickname: "Pine Tree State",
    capitol: "Augusta",
    area_sqkm: "91.633",
    rank_area: "39",
    population: "1.362.359",
    rank_population: "41",
    density_pop_per_sqkm: "14",
    join_date: "15. März 1820",
    gouveneur: "Janet T. Mills (D)"
  },
  {
    name: "Maryland",
    abr: "MD",
    nickname: "Old Line State",
    capitol: "Annapolis",
    area_sqkm: "32.131",
    rank_area: "42",
    population: "6.177.224",
    rank_population: "19",
    density_pop_per_sqkm: "180",
    join_date: "28. Apr. 1788",
    gouveneur: "Larry Hogan (R)"
  },
  {
    name: "Massachusetts",
    abr: "MA",
    nickname: "The Bay State",
    capitol: "Boston",
    area_sqkm: "27.336",
    rank_area: "44",
    population: "7.029.917",
    rank_population: "14",
    density_pop_per_sqkm: "240",
    join_date: "6. Feb. 1788",
    gouveneur: "Charlie Baker (R)"
  },
  {
    name: "Michigan",
    abr: "MI",
    nickname: "The Great Lakes State",
    capitol: "Lansing",
    area_sqkm: "250.487",
    rank_area: "11",
    population: "10.077.331",
    rank_population: "8",
    density_pop_per_sqkm: "39",
    join_date: "26. Jan. 1837",
    gouveneur: "Gretchen Whitmer (D)"
  },
  {
    name: "Minnesota",
    abr: "MN",
    nickname: "North Star State",
    capitol: "Saint Paul",
    area_sqkm: "225.163",
    rank_area: "12",
    population: "5.706.494",
    rank_population: "21",
    density_pop_per_sqkm: "24",
    join_date: "11. Mai 1858",
    gouveneur: "Tim Walz (D)"
  },
  {
    name: "Mississippi",
    abr: "MS",
    nickname: "Magnolia State",
    capitol: "Jackson",
    area_sqkm: "125.438",
    rank_area: "32",
    population: "2.961.279",
    rank_population: "31",
    density_pop_per_sqkm: "24",
    join_date: "10. Dez. 1817",
    gouveneur: "Tate Reeves (R)"
  },
  {
    name: "Missouri",
    abr: "MO",
    nickname: "Show-Me-State",
    capitol: "Jefferson City",
    area_sqkm: "180.540",
    rank_area: "21",
    population: "6.154.913",
    rank_population: "18",
    density_pop_per_sqkm: "33",
    join_date: "10. Aug. 1821",
    gouveneur: "Mike Parson (R)"
  },
  {
    name: "Montana",
    abr: "MT",
    nickname: "Treasure State",
    capitol: "Helena",
    area_sqkm: "380.831",
    rank_area: "4",
    population: "1.084.225",
    rank_population: "44",
    density_pop_per_sqkm: "3",
    join_date: "8. Nov. 1889",
    gouveneur: "Greg Gianforte (R)"
  },
  {
    name: "Nebraska",
    abr: "NE",
    nickname: "Cornhusker State",
    capitol: "Lincoln",
    area_sqkm: "200.330",
    rank_area: "16",
    population: "1.961.504",
    rank_population: "38",
    density_pop_per_sqkm: "9",
    join_date: "1. März 1867",
    gouveneur: "Pete Ricketts (R)"
  },
  {
    name: "Nevada",
    abr: "NV",
    nickname: "Silver State",
    capitol: "Carson City",
    area_sqkm: "286.380",
    rank_area: "7",
    population: "3.104.614",
    rank_population: "35",
    density_pop_per_sqkm: "9",
    join_date: "31. Okt. 1864",
    gouveneur: "Steve Sisolak (D)"
  },
  {
    name: "New Hampshire",
    abr: "NH",
    nickname: "Granite State",
    capitol: "Concord",
    area_sqkm: "24.214",
    rank_area: "46",
    population: "1.377.529",
    rank_population: "42",
    density_pop_per_sqkm: "54",
    join_date: "21. Juni 1788",
    gouveneur: "Chris Sununu (R)"
  },
  {
    name: "New Jersey",
    abr: "NJ",
    nickname: "Garden State",
    capitol: "Trenton",
    area_sqkm: "22.591",
    rank_area: "47",
    population: "9.288.994",
    rank_population: "11",
    density_pop_per_sqkm: "389",
    join_date: "18. Dez. 1787",
    gouveneur: "Phil Murphy (D)"
  },
  {
    name: "New Mexico",
    abr: "NM",
    nickname: "Land of Enchantment",
    capitol: "Santa Fe",
    area_sqkm: "314.917",
    rank_area: "5",
    population: "2.117.522",
    rank_population: "36",
    density_pop_per_sqkm: "7",
    join_date: "6. Jan. 1912",
    gouveneur: "Michelle Lujan Grisham (D)"
  },
  {
    name: "New York",
    abr: "NY",
    nickname: "The Empire State",
    capitol: "Albany",
    area_sqkm: "141.297",
    rank_area: "27",
    population: "20.201.249",
    rank_population: "4",
    density_pop_per_sqkm: "137",
    join_date: "26. Juli 1788",
    gouveneur: "Kathy Hochul (D)"
  },
  {
    name: "North Carolina",
    abr: "NC",
    nickname: "Tar Heel State",
    capitol: "Raleigh",
    area_sqkm: "139.391",
    rank_area: "28",
    population: "10.439.388",
    rank_population: "10",
    density_pop_per_sqkm: "68",
    join_date: "21. Nov. 1789",
    gouveneur: "Roy Cooper (D)"
  },
  {
    name: "North Dakota",
    abr: "ND",
    nickname: "Peace Garden State",
    capitol: "Bismarck",
    area_sqkm: "183.108",
    rank_area: "19",
    population: "779.094",
    rank_population: "48",
    density_pop_per_sqkm: "4",
    join_date: "2. Nov. 1889",
    gouveneur: "Doug Burgum (R)"
  },
  {
    name: "Ohio",
    abr: "OH",
    nickname: "Buckeye State",
    capitol: "Columbus",
    area_sqkm: "116.098",
    rank_area: "34",
    population: "11.799.448",
    rank_population: "7",
    density_pop_per_sqkm: "99",
    join_date: "1. März 1803",
    gouveneur: "Mike DeWine (R)"
  },
  {
    name: "Oklahoma",
    abr: "OK",
    nickname: "Native America",
    capitol: "Oklahoma City",
    area_sqkm: "181.037",
    rank_area: "20",
    population: "3.959.353",
    rank_population: "28",
    density_pop_per_sqkm: "21",
    join_date: "16. Nov. 1907",
    gouveneur: "Kevin Stitt (R)"
  },
  {
    name: "Oregon",
    abr: "OR",
    nickname: "Beaver State",
    capitol: "Salem",
    area_sqkm: "254.799",
    rank_area: "9",
    population: "4.237.256",
    rank_population: "27",
    density_pop_per_sqkm: "15",
    join_date: "14. Feb. 1859",
    gouveneur: "Kate Brown (D)"
  },
  {
    name: "Pennsylvania",
    abr: "PA",
    nickname: "Keystone State",
    capitol: "Harrisburg",
    area_sqkm: "119.280",
    rank_area: "33",
    population: "13.002.700",
    rank_population: "6",
    density_pop_per_sqkm: "106",
    join_date: "12. Dez. 1787",
    gouveneur: "Tom Wolf (D)"
  },
  {
    name: "Rhode Island",
    abr: "RI",
    nickname: "Ocean State",
    capitol: "Providence",
    area_sqkm: "4.001",
    rank_area: "50",
    population: "1.097.379",
    rank_population: "43",
    density_pop_per_sqkm: "263",
    join_date: "29. Mai 1790",
    gouveneur: "Daniel McKee (D)"
  },
  {
    name: "South Carolina",
    abr: "SC",
    nickname: "Palmetto State",
    capitol: "Columbia",
    area_sqkm: "82.933",
    rank_area: "40",
    population: "5.118.425",
    rank_population: "24",
    density_pop_per_sqkm: "56",
    join_date: "23. Mai 1788",
    gouveneur: "Henry McMaster (R)"
  },
  {
    name: "South Dakota",
    abr: "SD",
    nickname: "Mount Rushmore State",
    capitol: "Pierre",
    area_sqkm: "199.729",
    rank_area: "17",
    population: "886.667",
    rank_population: "46",
    density_pop_per_sqkm: "4",
    join_date: "2. Nov. 1889",
    gouveneur: "Kristi Noem (R)"
  },
  {
    name: "Tennessee",
    abr: "TN",
    nickname: "Volunteer State",
    capitol: "Nashville",
    area_sqkm: "109.153",
    rank_area: "36",
    population: "6.910.840",
    rank_population: "17",
    density_pop_per_sqkm: "58",
    join_date: "1. Juni 1796",
    gouveneur: "Bill Lee (R)"
  },
  {
    name: "Texas",
    abr: "TX",
    nickname: "Lone Star State",
    capitol: "Austin",
    area_sqkm: "695.662",
    rank_area: "2",
    population: "29.145.505",
    rank_population: "2",
    density_pop_per_sqkm: "36",
    join_date: "29. Dez. 1845",
    gouveneur: "Greg Abbott (R)"
  },
  {
    name: "Utah",
    abr: "UT",
    nickname: "Beehive State",
    capitol: "Salt Lake City",
    area_sqkm: "219.882",
    rank_area: "13",
    population: "3.271.616",
    rank_population: "34",
    density_pop_per_sqkm: "13",
    join_date: "4. Jan. 1896",
    gouveneur: "Spencer Cox (R)"
  },
  {
    name: "Vermont",
    abr: "VT",
    nickname: "Green Mountain State",
    capitol: "Montpelier",
    area_sqkm: "24.906",
    rank_area: "45",
    population: "643.077",
    rank_population: "49",
    density_pop_per_sqkm: "25",
    join_date: "4. März 1791",
    gouveneur: "Phil Scott (R)"
  },
  {
    name: "Virginia",
    abr: "VA",
    nickname: "The Old Dominion",
    capitol: "Richmond",
    area_sqkm: "110.787",
    rank_area: "35",
    population: "8.631.393",
    rank_population: "12",
    density_pop_per_sqkm: "72",
    join_date: "25. Juni 1788",
    gouveneur: "Glenn Youngkin (R)"
  },
  {
    name: "Washington",
    abr: "WA",
    nickname: "Evergreen State",
    capitol: "Olympia",
    area_sqkm: "184.661",
    rank_area: "18",
    population: "7.705.281",
    rank_population: "13",
    density_pop_per_sqkm: "36",
    join_date: "11. Nov. 1889",
    gouveneur: "Jay Inslee (D)"
  },
  {
    name: "West Virginia",
    abr: "WV",
    nickname: "Mountain State",
    capitol: "Charleston",
    area_sqkm: "62.756",
    rank_area: "41",
    population: "1.793.716",
    rank_population: "37",
    density_pop_per_sqkm: "30",
    join_date: "20. Juni 1863",
    gouveneur: "Jim Justice (R)"
  },
  {
    name: "Wisconsin",
    abr: "WI",
    nickname: "America's Dairyland",
    capitol: "Madison",
    area_sqkm: "169.635",
    rank_area: "23",
    population: "5.893.718",
    rank_population: "20",
    density_pop_per_sqkm: "34",
    join_date: "29. Mai 1848",
    gouveneur: "Tony Evers (D)"
  },
  {
    name: "Wyoming",
    abr: "WY",
    nickname: "Equality State",
    capitol: "Cheyenne",
    area_sqkm: "253.335",
    rank_area: "10",
    population: "576.851",
    rank_population: "50",
    density_pop_per_sqkm: "2",
    join_date: "10. Juli 1890",
    gouveneur: "Mark Gordon (R)"
  }
];
